### ISSUE TITLE
Separate Query and Mutation resolvers

### ISSUE THREAD

**Issue by belka-ew** [caraus-ecms/graphql#33]
All resolvers are currently saved in a single `NonEmpty` list.

The one way would be to represent each resolver as a sum type:

```haskell
data Resolver = Query ... | Mutation ... | Subscription
type Resolvers = NonEmpty Resolver
```

The another one is to have 3 hashmaps:

```haskell
data Resolvers = Resolvers
{ quries :: HashMap Text Resolver
, mutations :: HashMap Text Resolver
, subscriptions :: HashMap Text Resolver
}
```

The latter one is preferable, since it makes lookups easy. Currently I'm doing a very ugly thing and iterate all the resolvers each time looking for the right one.

It is also the first step towards subscriptions. Subscriptions shouldn't be as difficult to implement as I thought. They just need a special resolver that returns a special state (or stream in terms of GraphQL), that can be used to execute the resolver multiple times.

The change should be combined with redesigning resolver arguments, so we don't break the resolvers each release.

**Comment by Hazelfire** [comment]
Yes please! This confused me the first time I used the library and I had to look at the source code to understand why there was only one set of resolvers. I might just code this now.

**Comment by Hazelfire** [comment]
It just dawned on me while I'm implementing this that this is going to have a very real impact on the user is going to use this library, particularly with the idea of changing NonEmpty lists to HashMaps, as entire schemas would need to be represented at HashMaps rather than lists of resolvers, unless I'm mistaken...

I think it might be worth splitting this feature into two pull requests, one for splitting up query, mutations and resolvers, and one for moving the entire library to HashMaps

**Comment by belka-ew** [comment]
You can do it as you like. If you're more comfortable with small steps (I would probably do it like this), you can just convert between the hashmaps and lists. A list of tuples `(Text, Resolver)` can be converted to a `HashMap`, and a HashMap to a list of tuples. It will destroy the order, but the order doesn't matter in this case.

Subscirptions can be probably ignored for now.

`NonEmpty Resolver` can be replaced with these 2-3 HashMaps directly, but I would keep the signature of `Schema.object`, `Schema.wrappedObject` and Co. as is and convert the given lists to hashmaps internally, imho it would be more difficult for the user to write hashmaps everywhere. Until we don't have a nicer method to write the resolvers (something like `ToJSON` and `FromJSON` in Aeson),  I would keep the lists, since they are a bit easier to work with.

yeah, modifying `Schema.resolve` is probably a separate issue, you can just convert the queries and mutations to 2 lists and merge them. Current tests should pass then and after that we can change `resolve` as well. I hope hashmaps would also make the logic in `resolve` simpler, it looks a bit terrible currently :(

**Comment by belka-ew** [comment]
I have chosen `HashMap Text (NonEmpty (Resolver m)`, where the Text argument is "Query" or "Mutation".
Any object type can be the root operation type, so my original proposal wouldn't work in the long run, since the schema can define many types and not only 3, and any of thise types can be a root operation type (query, mutation or subscription).
