### ISSUE TITLE
Strings that contain control sequences shouldn't be encoded as block strings

### ISSUE THREAD

**Issue by belka-ew** [caraus-ecms/graphql#39]
Block strings can only contain `BlockStringCharacter`, that is `SourceCharacter` and `\"""`. `SourceCharacter` is defined as `/[\u0009\u000A\u000D\u0020-\uFFFF]/`. That is blockstrings can't contain control characters. The prettifier should check whether the string contains newlines or control characters:

1. If the string doesn't contain any newlines, encode as normal string
2. If the string contains not allowed control characters, encode as normal string
3. Encode as block string

**Comment by nishirken** [comment]
https://github.com/caraus-ecms/graphql/pull/41
